project:
  type: website
  output-dir: docs

website:
  title: "Jane Roe"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects and Publications
      - href: media/Resume_JoseNino.pdf
        text: CV

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
